
project_id = "ldlgckwkdsvrfuymidrr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
hook_timeout_ms = 10000

[auth.email]
enable_signup = true 
enable_confirmations = true
double_confirm_changes = true
template_create_user = "Your sign-up to Learnable was successful! Please verify your email."

[[edge_functions]]
name = "ask-ai"
verify_jwt = true

[[edge_functions]]
name = "save-chat-message"
verify_jwt = true

[[edge_functions]]
name = "get-chat-history"
verify_jwt = true

[[edge_functions]]
name = "get-conversations"
verify_jwt = true

[[edge_functions]]
name = "process-document"
verify_jwt = true

[[edge_functions]]
name = "transcribe-audio"
verify_jwt = true

[[edge_functions]]
name = "text-to-speech"
verify_jwt = true

[[edge_functions]]
name = "register-school"
verify_jwt = false

[[edge_functions]]
name = "create-test-accounts"
verify_jwt = false

[[edge_functions]]
name = "remove-user"
verify_jwt = true
