
project_id = "ldlgckwkdsvrfuymidrr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[edge_functions]]
name = "ask-ai"
verify_jwt = true

[[edge_functions]]
name = "save-chat-message"
verify_jwt = true

[[edge_functions]]
name = "get-chat-history"
verify_jwt = true

[[edge_functions]]
name = "get-conversations"
verify_jwt = true

[[edge_functions]]
name = "process-document"
verify_jwt = true

[[edge_functions]]
name = "transcribe-audio"
verify_jwt = true

[[edge_functions]]
name = "text-to-speech"
verify_jwt = true
