
project_id = "ldlgckwkdsvrfuymidrr"

[functions.invite-teacher]
verify_jwt = true

[functions.create-teacher]
verify_jwt = true

[functions.generate-student-invite]
verify_jwt = true

[functions.approve-student]
verify_jwt = true

[functions.revoke-student-access]
verify_jwt = true

[functions.create-session-log]
verify_jwt = true

[functions.update-session]
verify_jwt = true

[functions.end-session]
verify_jwt = true
