
project_id = "ldlgckwkdsvrfuymidrr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true

[realtime]
enabled = true

[auth]
site_url = "https://your-app-domain.com"
additional_redirect_urls = [
  "https://your-app-domain.com/auth/callback", 
  "http://localhost:5173/auth/callback"
]
