
project_id = "ldlgckwkdsvrfuymidrr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[functions]
[functions.register-school]
verify_jwt = false
[functions.resend-verification]
verify_jwt = false
[functions.create-school-admin]
verify_jwt = false

[auth]
enabled = true
port = 54326
