
project_id = "ldlgckwkdsvrfuymidrr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true

[realtime]
enabled = true

[auth]
site_url = "https://your-published-site-url.com"
additional_redirect_urls = ["https://your-published-site-url.com/auth/callback"]
