import React, { useState, useEffect, useRef } from 'react';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Send, Loader2, Key, Copy, CheckCircle } from "lucide-react";
import { useToast } from "@/components/ui/use-toast";
import { useAuth } from "@/contexts/AuthContext";
import { useChat } from 'ai/react';
import { Textarea } from "@/components/ui/textarea";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form"
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod"
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"
import { Slider } from "@/components/ui/slider"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Separator } from "@/components/ui/separator"
import { Badge } from "@/components/ui/badge"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { ScrollArea } from "@/components/ui/scroll-area"
import { useSettings } from "@/contexts/SettingsContext";
import { useCompletion } from 'ai/react';
import { useUser } from '@/hooks/use-user';
import { supabase } from '@/integrations/supabase/client';
import { safeApiKeyAccess } from '@/utils/supabaseTypeHelpers';

const AIChatInterface = () => {
  const { toast } = useToast();
  const { user } = useAuth();
  const { settings, refreshUserSettings } = useSettings();
  const [showApiKeyForm, setShowApiKeyForm] = useState(false);
  const [apiKeySaving, setApiKeySaving] = useState(false);
  const [isCopied, setIsCopied] = useState(false);
  const bottomRef = useRef<HTMLDivElement>(null);
  const [isInitialLoad, setIsInitialLoad] = useState(true);
  const [isSettingsLoading, setIsSettingsLoading] = useState(false);
  const [apiKey, setApiKey] = useState<string | null>(null);
  const [provider, setProvider] = useState<string | null>(null);
  const [isApiKeyValid, setIsApiKeyValid] = useState(true);
  const [apiKeyError, setApiKeyError] = useState<string | null>(null);
  const [isGeminiAvailable, setIsGeminiAvailable] = useState(false);
  const [isGPTAvailable, setIsGPTAvailable] = useState(false);
  const [isApiKeyLoading, setIsApiKeyLoading] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isApiKeyPopoverOpen, setIsApiKeyPopoverOpen] = useState(false);
  const [isSettingsPopoverOpen, setIsSettingsPopoverOpen] = useState(false);
  const [isModelPopoverOpen, setIsModelPopoverOpen] = useState(false);
  const [isTemperaturePopoverOpen, setIsTemperaturePopoverOpen] = useState(false);
  const [isMaxTokensPopoverOpen, setIsMaxTokensPopoverOpen = useState(false);
  const [isSourcesPopoverOpen, setIsSourcesPopoverOpen = useState(false);
  const [isStreaming, setIsStreaming] = useState(false);
  const [isResetting, setIsResetting] = useState(false);
  const [isPromptCopied, setIsPromptCopied] = useState(false);
  const [isResponseCopied, setIsResponseCopied] = useState(false);
  const [isSettingsCopied, setIsSettingsCopied] = useState(false);
  const [isModelCopied, setIsModelCopied] = useState(false);
  const [isTemperatureCopied, setIsTemperatureCopied] = useState(false);
  const [isMaxTokensCopied, setIsMaxTokensCopied = useState(false);
  const [isSourcesCopied, setIsSourcesCopied = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPromptPopoverCopied, setIsPromptPopoverCopied] = useState(false);
  const [isResponsePopoverCopied, setIsResponsePopoverCopied] = useState(false);
  const [isPromptPopoverOpen, setIsPromptPopoverOpen] = useState(false);
  const [isResponsePopoverOpen, setIsResponsePopoverOpen] = useState(false);
  const [isSettingsPopoverCopied, setIsSettingsPopoverCopied] = useState(false);
  const [isModelPopoverCopied, setIsModelPopoverCopied] = useState(false);
  const [isTemperaturePopoverCopied, setIsTemperaturePopoverCopied] = useState(false);
  const [isMaxTokensPopoverCopied = useState(false), setIsMaxTokensPopoverCopied] = useState(false);
  const [isSourcesPopoverCopied, setIsSourcesPopoverCopied] = useState(false);
  const [isPrompt
